theme: hugo-theme-red-rose
baseURL: http://example.org/
languageCode: en
title: Felix (Chen-Wei) Yu
PygmentsCodeFences: yes
PygmentsStyle: solarized-dark256
pluralizelisttitles: 'false'
pagination.pagerSize: 2
disableHugoGeneratorInject: yes
params:
  ava: /img/profile.JPG
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
publishDir: "docs"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
markup:
  goldmark:
    renderer:
      unsafe: true