---
draft: false
---

# I am a PhD candidate at _Norhwestern University_. My research is motivated by two broad questions: (1) why and how people regulate their own and others' emotions, and (2) what are the consequences of emotion regulation at the individual, interpersonal, and societal levels.


  1. Why and how people regulate their own and others' emotions? For instance, why are some emotions expressed more than others? What goals drive people's emotion expression vs. suppression?  
  
  2. What are the consequences of motivated emotion regulation, at the individual, interpersonal, and societal levels? For instance, how does emotion regulation affect people's short- and long-term well-being? How does it affect people's relationships with others at different stages, from initiation, maintenance, and even dissolution? More recently, I've been exploring the processes in which individuals' emotion regulation scales up to affect social changes, such as the rise of social movements. 

I use a variety of methods to address my research questions, spanning across traditional quantitative tools (e.g., survey experiment, daily dairy, structural equational modeling, etc.) to computational approaches (e.g., text analysis, network analysis, etc.). I value both data-driven insights and theory-guided explanations. 

I have intensive quantitative and computational training in creating psychometrically sound measures along with validating and refining existing ones. I am also well-trained in fitting models that are both statistically correct and grounded in psychological theories to the data. My work is both exploratory and confirmatory in nature, and I value both predictability and explanbility.  

See [here](/blog/2022-12-11-publication/publication/) for a list of publication. 
